
services:
  - type: web
    name: campeggio-santa-margherita
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
